name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.4'
        cache: 'true'
        install-deps: 'true'
        setup-python: 'false'
        modules: 'qtcharts qtmultimedia'
        
    - name: install_qt_deps
      run: sudo apt-get install libgstreamer-gl1.0-0

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu
        path: ${{github.workspace}}/build
        
  build_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.4'
        cache: 'true'
        install-deps: 'true'
        setup-python: 'false'
        modules: 'qtcharts qtmultimedia'
        

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        cp ${{env.Qt6_DIR}}/bin/Qt6Charts.dll ${{github.workspace}}/build/Release
        cp ${{env.Qt6_DIR}}/bin/Qt6Core.dll ${{github.workspace}}/build/Release
        cp ${{env.Qt6_DIR}}/bin/Qt6Gui.d:ll ${{github.workspace}}/build/Release
        cp ${{env.Qt6_DIR}}/bin/Qt6Multimedia.dll ${{github.workspace}}/build/Release
        cp ${{env.Qt6_DIR}}/bin/Qt6MultimediaWidgets.dll ${{github.workspace}}/build/Release
        cp ${{env.Qt6_DIR}}/bin/Qt6Network.dll ${{github.workspace}}/build/Release
        cp ${{env.Qt6_DIR}}/bin/Qt6OpenGL.dll ${{github.workspace}}/build/Release        
        cp ${{env.Qt6_DIR}}/bin/Qt6OpenGLWidgets.dll ${{github.workspace}}/build/Release
        cp ${{env.Qt6_DIR}}/bin/Qt6OpenGL.dll ${{github.workspace}}/build/Release
        cp ${{env.Qt6_DIR}}/bin/Qt6Widgets.dll ${{github.workspace}}/build/Release
        mkdir ${{github.workspace}}/build/Release/platforms
        cp ${{env.QT_PLUGIN_PATH}}/platforms/qwindows.dll ${{github.workspace}}/build/Release/platforms
        mkdir ${{github.workspace}}/build/Release/tls
        cp ${{env.QT_PLUGIN_PATH}}/tls/qschannelbackend.dll ${{github.workspace}}/build/Release/tls

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: ${{github.workspace}}\build\Release
