name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.4'
        cache: 'true'
        install-deps: 'true'
        setup-python: 'false'
        modules: 'qtcharts qtmultimedia'
        
    - name: install_qt_deps
      run: sudo apt-get install libgstreamer-gl1.0-0

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu-${{ vars.GITHUB_REF_NAME }}
        path: /home/runner/work/GoProSurf/GoProSurf/build/GoProSurf
        
  build_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.4'
        cache: 'true'
        install-deps: 'true'
        setup-python: 'false'
        modules: 'qtcharts qtmultimedia'
        

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        env
        ls D:\a\GoProSurf
        cp D:\Qt\6.2.4\msvc2019_64\bin\Qt6Chartsd.dll D:\a\GoProSurf\GoProSurf\build\Release
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-${{ vars.GITHUB_REF_NAME }}
        path: D:\a\GoProSurf\GoProSurf\build\Release
